In [338]:
import pandas as pd

In [339]:
email=pd.read_csv("E:/Krish course materials/Gen AI/Spam Ham email Prediction/spamhamdata.csv",sep='\t',names=["label","message"])
email.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

Swapping the columns

In [340]:
email=email[["message","label"]]

In [341]:
email.tail()

message label
5567  This is the 2nd time we have tried 2 contact u...  spam
5568               Will ü b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

In [343]:
email.isnull().sum()

message    0
label      0
dtype: int64

In [344]:
len(email)

5572

In [345]:
import re
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

Text Pre-processing using WordNet lemmatizer

In [346]:
corpus=[]

for i in range(len(email)):
    review=re.sub("[^a-zA-Z]"," ",email["message"][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=" ".join(review)
    corpus.append(review)


In [347]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus,email["message"]) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [348]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [349]:
len(corpus)

5572

In [282]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [350]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))


In [351]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [352]:
len(words)

5569

In [353]:
# Train Word2vec from scratch
import gensim
model=gensim.models.Word2Vec(words)

In [354]:
# To get all vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [355]:
model.corpus_count

5569

In [356]:
model.epochs

5

In [357]:
model.wv.similar_by_word("kid")

[('too', 0.9977103471755981),
 ('boy', 0.9976847767829895),
 ('yet', 0.9976716041564941),
 ('him', 0.9976520538330078),
 ('other', 0.9975497126579285),
 ('buy', 0.9975438714027405),
 ('always', 0.9975343942642212),
 ('amp', 0.9974870085716248),
 ('already', 0.9974755644798279),
 ('god', 0.9974719882011414)]

In [358]:
model.wv.similar_by_word("good")

[('night', 0.998338520526886),
 ('day', 0.9983165860176086),
 ('not', 0.998286783695221),
 ('of', 0.9981447458267212),
 ('happy', 0.9980878829956055),
 ('wa', 0.998071551322937),
 ('my', 0.9980472326278687),
 ('morning', 0.9980466365814209),
 ('all', 0.9980302453041077),
 ('about', 0.9980041980743408)]

In [359]:
model.wv['good']

array([-2.53658682e-01,  3.35847527e-01,  1.49658754e-01,  1.57160461e-01,
        9.03793499e-02, -6.43851280e-01,  2.37516671e-01,  6.54438794e-01,
       -3.72122347e-01, -1.48881808e-01, -2.08827510e-01, -5.52223802e-01,
       -6.01482391e-03,  1.40793726e-01,  2.57600576e-01, -2.42632911e-01,
        1.91443905e-01, -3.90551835e-01, -2.45652553e-02, -7.75087178e-01,
        3.58086169e-01,  1.72543213e-01,  1.88726142e-01, -2.78338611e-01,
       -2.06510108e-02,  4.11205366e-03, -2.67396033e-01, -3.04429621e-01,
       -3.48676771e-01,  5.94023131e-02,  4.65692341e-01,  1.27490833e-02,
        1.86993390e-01, -2.38201246e-01, -1.34806931e-01,  6.00680888e-01,
        8.17598701e-02, -1.58335179e-01, -1.47707656e-01, -6.19525850e-01,
        1.60566613e-01, -3.72750580e-01, -2.48851985e-01,  3.48163284e-02,
        2.22966045e-01, -2.80334093e-02, -2.30086148e-01, -9.68241543e-02,
        2.89548934e-01,  1.60376176e-01,  3.17901224e-01, -2.90437847e-01,
       -1.16146930e-01,  

In [360]:
model.wv['good'].shape

(100,)

In [364]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [362]:
import numpy as np

In [365]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent= [word for word in doc if word in model.wv.index_to_key]
    #print(sent)

    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [366]:
from tqdm import tqdm

In [367]:
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  6%|▌         | 338/5569 [00:00<00:04, 1264.93it/s]c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:03<00:00, 1690.12it/s]


In [368]:
X

[array([-0.1767934 ,  0.22365186,  0.11052799,  0.10082313,  0.07943054,
        -0.47356072,  0.15456289,  0.4538407 , -0.26102865, -0.12925632,
        -0.15234706, -0.37838534, -0.04493741,  0.10606921,  0.17895082,
        -0.15997028,  0.11470608, -0.29574242, -0.02255342, -0.5345051 ,
         0.2052709 ,  0.11190315,  0.11344449, -0.20741193, -0.01418872,
         0.00449877, -0.209706  , -0.20589146, -0.25026816,  0.04442757,
         0.31365636,  0.01404291,  0.11151244, -0.16307122, -0.10485335,
         0.41857374,  0.07811839, -0.12627701, -0.13673264, -0.44142446,
         0.10375641, -0.25597802, -0.18582623,  0.02025993,  0.15157133,
        -0.03806092, -0.14639683, -0.05923158,  0.22219801,  0.10914729,
         0.19869302, -0.21305919, -0.0624951 ,  0.06438358, -0.11214922,
         0.07035209,  0.16400267, -0.01223667, -0.42765388,  0.13976797,
        -0.00738461,  0.16220169,  0.00646683, -0.10436884, -0.31710616,
         0.2973805 ,  0.05771436,  0.24653667, -0.3

Identifing Nan rows after Avgword2 Vec

In [376]:
for index,i in enumerate(X):
    if np.isnan(i).any():
        print(index,i)

451 nan
783 nan
2102 nan
2569 nan
3269 nan
3740 nan
3979 nan
4291 nan
4478 nan
4620 nan
5170 nan
5411 nan


In [377]:
len(X)

5569

In [381]:
X_cleaned = [arr for arr in X if arr is not None and arr.size > 0 and not np.isnan(arr).any()]

In [382]:
len(X_cleaned)

5557

In [383]:
X_cleaned

[array([-0.1767934 ,  0.22365186,  0.11052799,  0.10082313,  0.07943054,
        -0.47356072,  0.15456289,  0.4538407 , -0.26102865, -0.12925632,
        -0.15234706, -0.37838534, -0.04493741,  0.10606921,  0.17895082,
        -0.15997028,  0.11470608, -0.29574242, -0.02255342, -0.5345051 ,
         0.2052709 ,  0.11190315,  0.11344449, -0.20741193, -0.01418872,
         0.00449877, -0.209706  , -0.20589146, -0.25026816,  0.04442757,
         0.31365636,  0.01404291,  0.11151244, -0.16307122, -0.10485335,
         0.41857374,  0.07811839, -0.12627701, -0.13673264, -0.44142446,
         0.10375641, -0.25597802, -0.18582623,  0.02025993,  0.15157133,
        -0.03806092, -0.14639683, -0.05923158,  0.22219801,  0.10914729,
         0.19869302, -0.21305919, -0.0624951 ,  0.06438358, -0.11214922,
         0.07035209,  0.16400267, -0.01223667, -0.42765388,  0.13976797,
        -0.00738461,  0.16220169,  0.00646683, -0.10436884, -0.31710616,
         0.2973805 ,  0.05771436,  0.24653667, -0.3

In [384]:
#Independent features
X_new=np.array(X_cleaned)

In [392]:
X_new

array([[-0.1767934 ,  0.22365186,  0.11052799, ..., -0.16231008,
         0.15233429,  0.00771389],
       [-0.1641568 ,  0.19483009,  0.09387423, ..., -0.15121995,
         0.13820967,  0.00192177],
       [-0.18343021,  0.23476416,  0.11330425, ..., -0.19608265,
         0.1905374 ,  0.01943312],
       ...,
       [-0.23912992,  0.3061221 ,  0.14698267, ..., -0.20131674,
         0.19126384,  0.00658412],
       [-0.21585356,  0.26991725,  0.13070172, ..., -0.1952082 ,
         0.17894742,  0.003568  ],
       [-0.24143133,  0.29071167,  0.14311153, ..., -0.21430938,
         0.1911317 ,  0.00400935]], dtype=float32)

In [390]:
X_new.shape

(5557, 100)

In [ ]:
# Dependent Features
y= email[list(map(lambda x: len(x)>0,corpus))]
y=pd.get_dummies(y["label"])
y.drop(index=[451,783,2102,2569,3269,3740,3979,4291,4478,4620,5170,5411],inplace=True)
y=y.iloc[:,1].values

In [388]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [389]:
y.shape

(5557,)

In [ ]:
X_new[0].reshape(1,-1).shape

In [399]:
df = pd.DataFrame()

for i in range(len(X_new)):
    # Create a new DataFrame from X_new[i] and concatenate
    new_row = pd.DataFrame(X_new[i].reshape(1, -1))
    df = pd.concat([df, new_row], ignore_index=True)

In [400]:
df

0         1         2         3         4         5         6   \
0    -0.176793  0.223652  0.110528  0.100823  0.079431 -0.473561  0.154563   
1    -0.164157  0.194830  0.093874  0.088458  0.075927 -0.411064  0.121896   
2    -0.183430  0.234764  0.113304  0.116749  0.066064 -0.515389  0.147841   
3    -0.244306  0.304107  0.145610  0.140985  0.111323 -0.638954  0.203644   
4    -0.212785  0.249881  0.127923  0.116204  0.102780 -0.537124  0.170713   
...        ...       ...       ...       ...       ...       ...       ...   
5552 -0.208203  0.273092  0.145315  0.134155  0.085586 -0.575427  0.181085   
5553 -0.214369  0.258724  0.125735  0.127639  0.098809 -0.572361  0.178468   
5554 -0.239130  0.306122  0.146983  0.128626  0.098661 -0.623686  0.208805   
5555 -0.215854  0.269917  0.130702  0.124858  0.094043 -0.571194  0.180701   
5556 -0.241431  0.290712  0.143112  0.137576  0.106617 -0.622806  0.196041   

            7         8         9   ...        90        91        92  \
0     0.453841 -0.261029 -0.129256  ...  0.343670  0.191046  0.026783   
1     0.399482 -0.227265 -0.104397  ...  0.305859  0.158366  0.018788   
2     0.438848 -0.275373 -0.160149  ...  0.340484  0.198600  0.013618   
3     0.620604 -0.356952 -0.164368  ...  0.468895  0.254271  0.034749   
4     0.524914 -0.301936 -0.145246  ...  0.400019  0.213627  0.032578   
...        ...       ...       ...  ...       ...       ...       ...   
5552  0.522060 -0.317032 -0.172280  ...  0.402792  0.229019  0.029276   
5553  0.537312 -0.320746 -0.151869  ...  0.411737  0.229526  0.015641   
5554  0.607037 -0.345314 -0.174090  ...  0.459822  0.261331  0.044355   
5555  0.541965 -0.312284 -0.162839  ...  0.408074  0.230519  0.037339   
5556  0.593682 -0.337747 -0.175048  ...  0.442553  0.247123  0.037863   

            93        94        95        96        97        98        99  
0     0.052694  0.422943  0.193171  0.182173 -0.162310  0.152334  0.007714  
1     0.039427  0.356649  0.162639  0.161201 -0.151220  0.138210  0.001922  
2     0.031034  0.432122  0.179664  0.125296 -0.196083  0.190537  0.019433  
3     0.076770  0.560018  0.263182  0.264212 -0.223730  0.204311  0.005019  
4     0.065854  0.474158  0.226914  0.212945 -0.199480  0.168729  0.006126  
...        ...       ...       ...       ...       ...       ...       ...  
5552  0.045366  0.504739  0.216547  0.172375 -0.208487  0.199028  0.022406  
5553  0.055038  0.501127  0.226350  0.192833 -0.214389  0.193163  0.015261  
5554  0.080794  0.562141  0.265486  0.261019 -0.201317  0.191264  0.006584  
5555  0.065943  0.505879  0.235126  0.211646 -0.195208  0.178947  0.003568  
5556  0.069713  0.551464  0.262015  0.234828 -0.214309  0.191132  0.004009  

[5557 rows x 100 columns]

In [401]:
df.shape

(5557, 100)

In [402]:
#Indepenent feature
X=df

Train Test Split

In [403]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [404]:
y_train

array([1, 0, 1, ..., 0, 0, 0], dtype=uint8)

Choosing Random Forest Classifer

In [405]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()

In [406]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [408]:
y_pred=classifier.predict(X_test)

In [414]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [410]:
accuracy_score(y_test,y_pred)

0.9739208633093526

In [412]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       965
           1       0.91      0.89      0.90       147

    accuracy                           0.97      1112
   macro avg       0.95      0.94      0.94      1112
weighted avg       0.97      0.97      0.97      1112



In [415]:
confusion_matrix(y_test,y_pred)

array([[952,  13],
       [ 16, 131]], dtype=int64)