In [1]:
import pandas as pd

In [2]:
email=pd.read_csv("E:/Krish course materials/Gen AI/Spam Ham email Prediction/spamhamdata.csv",sep='\t',names=["label","message"])
email.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

Swapping the columns

In [3]:
email=email[["message","label"]]

In [4]:
email.tail()

message label
5567  This is the 2nd time we have tried 2 contact u...  spam
5568               Will ü b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

In [5]:
email.isnull().sum()

message    0
label      0
dtype: int64

In [6]:
len(email)

5572

In [7]:
import re
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

Text Pre-processing using WordNet lemmatizer

In [9]:
corpus=[]

for i in range(len(email)):
    review=re.sub("[^a-zA-Z]"," ",email["message"][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=" ".join(review)
    corpus.append(review)


In [10]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus,email["message"]) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [11]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [12]:
len(corpus)

5572

In [13]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))


In [15]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [16]:
len(words)

5569

Train Word2vec from scratch

In [17]:
import gensim
model=gensim.models.Word2Vec(words)

To get all vocabulary

In [18]:
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [19]:
model.corpus_count

5569

In [20]:
model.epochs

5

In [21]:
model.wv.similar_by_word("kid")

[('too', 0.9970791935920715),
 ('yet', 0.9969975352287292),
 ('boy', 0.9969841241836548),
 ('him', 0.9968503713607788),
 ('went', 0.9968275427818298),
 ('great', 0.9968169331550598),
 ('nice', 0.9968072175979614),
 ('place', 0.9967954158782959),
 ('always', 0.9967910647392273),
 ('many', 0.9967826008796692)]

In [22]:
model.wv.similar_by_word("good")

[('morning', 0.9983485341072083),
 ('night', 0.9983259439468384),
 ('wa', 0.9982593059539795),
 ('not', 0.9981978535652161),
 ('happy', 0.9981700778007507),
 ('got', 0.998160183429718),
 ('oh', 0.9980607032775879),
 ('about', 0.9980342388153076),
 ('well', 0.9979966282844543),
 ('very', 0.9979841709136963)]

In [23]:
model.wv['good']

array([-0.27191025,  0.35272038,  0.16535334,  0.18123929,  0.09347649,
       -0.65142316,  0.24311551,  0.67201436, -0.36891577, -0.15610576,
       -0.19856544, -0.5588181 , -0.0116533 ,  0.14678985,  0.27382508,
       -0.23349655,  0.17575113, -0.4116744 , -0.00309478, -0.80916923,
        0.34482676,  0.18234281,  0.19685964, -0.2962903 , -0.05034853,
        0.01198382, -0.26105183, -0.27748847, -0.34309226,  0.05953862,
        0.466402  ,  0.02416309,  0.17910622, -0.23952952, -0.14502299,
        0.5746092 ,  0.08601889, -0.17228971, -0.15304339, -0.64550936,
        0.16073143, -0.3666266 , -0.2538396 ,  0.03080463,  0.23806235,
       -0.00805319, -0.22110343, -0.11094526,  0.296668  ,  0.1625678 ,
        0.3146415 , -0.27759525, -0.11610875,  0.05730088, -0.11630601,
        0.10710094,  0.2581449 ,  0.0027648 , -0.613235  ,  0.18469301,
       -0.04952813,  0.22593144, -0.00777813, -0.14095859, -0.44056132,
        0.39832693,  0.12055869,  0.35628685, -0.46174622,  0.56

In [24]:
model.wv['good'].shape

(100,)

In [25]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [26]:
import numpy as np

Converting word2vec to Avg word2vec to train the model

In [27]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent= [word for word in doc if word in model.wv.index_to_key]
    #print(sent)

    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [30]:
X=[]
for i in range(len(words)):
    X.append(avg_word2vec(words[i]))

In [31]:
X

[array([-0.1862114 ,  0.23612277,  0.12084426,  0.11449471,  0.07891282,
        -0.47312874,  0.15805064,  0.4611269 , -0.25113517, -0.13005611,
        -0.14252046, -0.37833795, -0.04965787,  0.10534748,  0.18957692,
        -0.14973187,  0.10360038, -0.3027685 , -0.00599749, -0.5471059 ,
         0.19336149,  0.11588529,  0.11976504, -0.21184038, -0.034974  ,
         0.01311899, -0.19925074, -0.18196756, -0.23702107,  0.04471884,
         0.30876318,  0.0224637 ,  0.10236879, -0.16220926, -0.1077457 ,
         0.3930046 ,  0.08520534, -0.13005328, -0.13491377, -0.44915906,
         0.1030132 , -0.24620257, -0.19023997,  0.0207749 ,  0.15988596,
        -0.01619947, -0.13985738, -0.06647031,  0.21659018,  0.11280005,
         0.19176249, -0.20377326, -0.06169341,  0.06586751, -0.12252725,
         0.07147378,  0.16471669, -0.01354613, -0.42666012,  0.13154854,
        -0.01531403,  0.16046773,  0.00504716, -0.09246035, -0.30346692,
         0.27684703,  0.0657406 ,  0.23008639, -0.3

Identifing Nan rows after Avgword2 Vec

In [32]:
for index,i in enumerate(X):
    if np.isnan(i).any():
        print(index,i)

451 nan
783 nan
2102 nan
2569 nan
3269 nan
3740 nan
3979 nan
4291 nan
4478 nan
4620 nan
5170 nan
5411 nan


In [33]:
len(X)

5569

In [34]:
X_cleaned = [arr for arr in X if arr is not None and arr.size > 0 and not np.isnan(arr).any()]

In [35]:
len(X_cleaned)

5557

In [36]:
X_cleaned

[array([-0.1862114 ,  0.23612277,  0.12084426,  0.11449471,  0.07891282,
        -0.47312874,  0.15805064,  0.4611269 , -0.25113517, -0.13005611,
        -0.14252046, -0.37833795, -0.04965787,  0.10534748,  0.18957692,
        -0.14973187,  0.10360038, -0.3027685 , -0.00599749, -0.5471059 ,
         0.19336149,  0.11588529,  0.11976504, -0.21184038, -0.034974  ,
         0.01311899, -0.19925074, -0.18196756, -0.23702107,  0.04471884,
         0.30876318,  0.0224637 ,  0.10236879, -0.16220926, -0.1077457 ,
         0.3930046 ,  0.08520534, -0.13005328, -0.13491377, -0.44915906,
         0.1030132 , -0.24620257, -0.19023997,  0.0207749 ,  0.15988596,
        -0.01619947, -0.13985738, -0.06647031,  0.21659018,  0.11280005,
         0.19176249, -0.20377326, -0.06169341,  0.06586751, -0.12252725,
         0.07147378,  0.16471669, -0.01354613, -0.42666012,  0.13154854,
        -0.01531403,  0.16046773,  0.00504716, -0.09246035, -0.30346692,
         0.27684703,  0.0657406 ,  0.23008639, -0.3

Independent features

In [37]:
X_new=np.array(X_cleaned)

In [48]:
X_new[0]

array([-0.1862114 ,  0.23612277,  0.12084426,  0.11449471,  0.07891282,
       -0.47312874,  0.15805064,  0.4611269 , -0.25113517, -0.13005611,
       -0.14252046, -0.37833795, -0.04965787,  0.10534748,  0.18957692,
       -0.14973187,  0.10360038, -0.3027685 , -0.00599749, -0.5471059 ,
        0.19336149,  0.11588529,  0.11976504, -0.21184038, -0.034974  ,
        0.01311899, -0.19925074, -0.18196756, -0.23702107,  0.04471884,
        0.30876318,  0.0224637 ,  0.10236879, -0.16220926, -0.1077457 ,
        0.3930046 ,  0.08520534, -0.13005328, -0.13491377, -0.44915906,
        0.1030132 , -0.24620257, -0.19023997,  0.0207749 ,  0.15988596,
       -0.01619947, -0.13985738, -0.06647031,  0.21659018,  0.11280005,
        0.19176249, -0.20377326, -0.06169341,  0.06586751, -0.12252725,
        0.07147378,  0.16471669, -0.01354613, -0.42666012,  0.13154854,
       -0.01531403,  0.16046773,  0.00504716, -0.09246035, -0.30346692,
        0.27684703,  0.0657406 ,  0.23008639, -0.33117065,  0.37

In [39]:
X_new.shape

(5557, 100)

Dependent Features

In [40]:
y= email[list(map(lambda x: len(x)>0,corpus))]
y=pd.get_dummies(y["label"])
y.drop(index=[451,783,2102,2569,3269,3740,3979,4291,4478,4620,5170,5411],inplace=True)
y=y.iloc[:,1].values

In [43]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [44]:
y.shape

(5557,)

Creating a new DataFrame to train the model for X_new and y

In [47]:
df = pd.DataFrame(X_new)
df

0         1         2         3         4         5         6   \
0    -0.186211  0.236123  0.120844  0.114495  0.078913 -0.473129  0.158051   
1    -0.169419  0.203129  0.099740  0.097715  0.074729 -0.404576  0.121497   
2    -0.194832  0.250779  0.125054  0.133104  0.070704 -0.518989  0.155672   
3    -0.259528  0.321118  0.157892  0.158957  0.111459 -0.639935  0.204702   
4    -0.228323  0.264890  0.142538  0.133518  0.104648 -0.545680  0.171816   
...        ...       ...       ...       ...       ...       ...       ...   
5552 -0.218917  0.294629  0.159454  0.153747  0.087900 -0.583854  0.194480   
5553 -0.236328  0.273877  0.143741  0.147770  0.104812 -0.586786  0.177688   
5554 -0.255476  0.323983  0.161541  0.148538  0.099581 -0.632915  0.213855   
5555 -0.231965  0.290504  0.146527  0.144390  0.096352 -0.583390  0.187814   
5556 -0.260324  0.300148  0.156052  0.154643  0.113355 -0.627286  0.191548   

            7         8         9   ...        90        91        92  \
0     0.461127 -0.251135 -0.130056  ...  0.340274  0.184699  0.031207   
1     0.402323 -0.215587 -0.103022  ...  0.301313  0.148729  0.020057   
2     0.451453 -0.264169 -0.163153  ...  0.338428  0.194462  0.018084   
3     0.636975 -0.346686 -0.163057  ...  0.470959  0.245095  0.039840   
4     0.545871 -0.299076 -0.148793  ...  0.405550  0.207612  0.038565   
...        ...       ...       ...  ...       ...       ...       ...   
5552  0.537486 -0.306547 -0.176511  ...  0.401539  0.228117  0.037145   
5553  0.562136 -0.319477 -0.156437  ...  0.422935  0.227389  0.021288   
5554  0.622182 -0.337900 -0.179731  ...  0.456874  0.256296  0.051232   
5555  0.563156 -0.307948 -0.168274  ...  0.411165  0.227662  0.044337   
5556  0.610339 -0.331109 -0.180441  ...  0.444150  0.236708  0.039598   

            93        94        95        96        97        98        99  
0     0.059795  0.414578  0.194647  0.179693 -0.177306  0.149357  0.026460  
1     0.042873  0.347076  0.162040  0.153032 -0.163049  0.133104  0.017258  
2     0.039706  0.418038  0.182084  0.132754 -0.209852  0.175270  0.039917  
3     0.085699  0.555933  0.268400  0.259360 -0.244670  0.202224  0.030641  
4     0.072021  0.473305  0.230665  0.211064 -0.219903  0.167407  0.028234  
...        ...       ...       ...       ...       ...       ...       ...  
5552  0.059063  0.496141  0.222547  0.177123 -0.226104  0.191302  0.045580  
5553  0.061203  0.499258  0.234519  0.195018 -0.239295  0.187219  0.039795  
5554  0.091609  0.555689  0.267618  0.256517 -0.224755  0.192921  0.030195  
5555  0.075068  0.503797  0.239772  0.211398 -0.217118  0.177029  0.024843  
5556  0.073892  0.537470  0.260335  0.223048 -0.244960  0.186787  0.031372  

[5557 rows x 100 columns]

In [ ]:
df = pd.DataFrame()

for i in range(len(X_new)):
    df = pd.append(pd.DataFrame(X_new[i].reshape(1, -1)),ignore_index=True)

In [50]:
df.shape

(5557, 100)

Indepenent feature

In [51]:
X=df
X

0         1         2         3         4         5         6   \
0    -0.186211  0.236123  0.120844  0.114495  0.078913 -0.473129  0.158051   
1    -0.169419  0.203129  0.099740  0.097715  0.074729 -0.404576  0.121497   
2    -0.194832  0.250779  0.125054  0.133104  0.070704 -0.518989  0.155672   
3    -0.259528  0.321118  0.157892  0.158957  0.111459 -0.639935  0.204702   
4    -0.228323  0.264890  0.142538  0.133518  0.104648 -0.545680  0.171816   
...        ...       ...       ...       ...       ...       ...       ...   
5552 -0.218917  0.294629  0.159454  0.153747  0.087900 -0.583854  0.194480   
5553 -0.236328  0.273877  0.143741  0.147770  0.104812 -0.586786  0.177688   
5554 -0.255476  0.323983  0.161541  0.148538  0.099581 -0.632915  0.213855   
5555 -0.231965  0.290504  0.146527  0.144390  0.096352 -0.583390  0.187814   
5556 -0.260324  0.300148  0.156052  0.154643  0.113355 -0.627286  0.191548   

            7         8         9   ...        90        91        92  \
0     0.461127 -0.251135 -0.130056  ...  0.340274  0.184699  0.031207   
1     0.402323 -0.215587 -0.103022  ...  0.301313  0.148729  0.020057   
2     0.451453 -0.264169 -0.163153  ...  0.338428  0.194462  0.018084   
3     0.636975 -0.346686 -0.163057  ...  0.470959  0.245095  0.039840   
4     0.545871 -0.299076 -0.148793  ...  0.405550  0.207612  0.038565   
...        ...       ...       ...  ...       ...       ...       ...   
5552  0.537486 -0.306547 -0.176511  ...  0.401539  0.228117  0.037145   
5553  0.562136 -0.319477 -0.156437  ...  0.422935  0.227389  0.021288   
5554  0.622182 -0.337900 -0.179731  ...  0.456874  0.256296  0.051232   
5555  0.563156 -0.307948 -0.168274  ...  0.411165  0.227662  0.044337   
5556  0.610339 -0.331109 -0.180441  ...  0.444150  0.236708  0.039598   

            93        94        95        96        97        98        99  
0     0.059795  0.414578  0.194647  0.179693 -0.177306  0.149357  0.026460  
1     0.042873  0.347076  0.162040  0.153032 -0.163049  0.133104  0.017258  
2     0.039706  0.418038  0.182084  0.132754 -0.209852  0.175270  0.039917  
3     0.085699  0.555933  0.268400  0.259360 -0.244670  0.202224  0.030641  
4     0.072021  0.473305  0.230665  0.211064 -0.219903  0.167407  0.028234  
...        ...       ...       ...       ...       ...       ...       ...  
5552  0.059063  0.496141  0.222547  0.177123 -0.226104  0.191302  0.045580  
5553  0.061203  0.499258  0.234519  0.195018 -0.239295  0.187219  0.039795  
5554  0.091609  0.555689  0.267618  0.256517 -0.224755  0.192921  0.030195  
5555  0.075068  0.503797  0.239772  0.211398 -0.217118  0.177029  0.024843  
5556  0.073892  0.537470  0.260335  0.223048 -0.244960  0.186787  0.031372  

[5557 rows x 100 columns]

In [52]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

Train Test Split

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

Training the model (Random Forest Classifer)

In [54]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()

Training the Random Forest model with training data

In [56]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

Prediction on data

In [57]:
y_pred=classifier.predict(X_test)

In [58]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [59]:
accuracy_score(y_test,y_pred)

0.9658273381294964

In [60]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       952
           1       0.90      0.86      0.88       160

    accuracy                           0.97      1112
   macro avg       0.94      0.92      0.93      1112
weighted avg       0.97      0.97      0.97      1112



In [61]:
confusion_matrix(y_test,y_pred)

array([[937,  15],
       [ 23, 137]], dtype=int64)